### ISSUE TITLE
Are usernames allowed as attribution name?

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/wallpapers#65]
I'm working on a PR to add a photo I took and I was wondering if I can use my username as attribution. Currently I have it as "Allie ChildishGiant" and then a link to the unsplash page. Thanks for any guidance :)

**Comment by cassidyjames** [comment]
@ChildishGiant sorry about the long delay, there's not usually much activity on this repo :sweat_smile: 

I'd say yeah, if it's under the Unsplash license then any sort of attribution is fine (as attribution is not strictly required anyway). And since it's your work, you can attribute it however you'd like :)
